# Generated by Django 6.0.6 on 2026-06-26 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('original_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('duration_seconds', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'pending'),
                            ('PROCESSING', 'processing'),
                            ('READY', 'ready'),
                            ('FAILED', 'failed'),
                        ],
                        default='PENDING',
                        max_length=40,
                    ),
                ),
                (
                    'audio_file_path',
                    models.FileField(upload_to='music/audio/'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'media_source',
            },
        ),
    ]
