# Generated by Django 6.0.6 on 2026-07-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasource',
            name='audio_file_path',
            field=models.FileField(null=True, upload_to='music/audio/'),
        ),
        migrations.AlterField(
            model_name='mediasource',
            name='channel_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediasource',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
