# Generated by Django 6.0.6 on 2026-07-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_mediasource_audio_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasource',
            name='audio_file_path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
