# Generated by Django 6.0.6 on 2026-07-05 23:23

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_mediasource_audio_file_path'),
    ]

    operations = [
        TrigramExtension()
    ]
