# Generated by Django 6.0.6 on 2026-07-05 23:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_enable_trigram_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mediasource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='music_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='mediasource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['channel_name'], name='music_channel_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
